config/routes.rb
Relay::Application.routes.draw do

  resources :teams


  root to: 'Access#log_in', as: 'log_in'
  get "/access/remote_login", to: 'Access#remote_login'
  get "/access/log_out", to: 'Access#log_out', as: 'log_out'

  resources :users

  get "/home", to: 'Home#index' , as: 'homepage'

  get '/goal_page', to: 'Home#goal_page' , as: 'goal_page'

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  def log_in
  end

  def remote_login
    code = params[:code]
    response = HTTParty.post("https://runkeeper.com/apps/token?grant_type=authorization_code&code=#{code}&client_id=2352dbda60b94f7fa07649bded3aa8c2&client_secret=b2fae9603ac741dd9c3429f55af8568a&redirect_uri=http://localhost:3000/access/remote_login")
    token = response["access_token"]
    rkUser  = JSON.parse(HTTParty.get("https://api.runkeeper.com/user?access_token=#{token}"))
    rkProfile = JSON.parse(HTTParty.get("https://api.runkeeper.com/profile?access_token=#{token}"))
    user = User.find_by_rk_id(rkUser["userID"]) || User.create_from_rk(token, rkUser["userID"], rkProfile['name'])
    if user
      session[:user_id] = user.id
      session[:user_name] = user.name
      session[:access_token] = user.access_token
      redirect_to user_url(user.id)
    else
      redirect_to root_url, notice: "Log in error"
    end
  end

  def log_out
    reset_session
  end
end

app/views/access/log_in.html.erb
<%= link_to  "Sign in with RunKeeper", "https://runkeeper.com/apps/authorize?client_id=2352dbda60b94f7fa07649bded3aa8c2&response_type=code&redirect_uri=http://localhost:3000/access/remote_login" %>

app/views/access/log_out.html.erb
<p>Do you want to sign out of RunKeeper?</p>
<%= link_to "Yes", "http://runkeeper.com/logout", target: "_blank", id: "logout_runkeeper" %>
<%= link_to "No", log_in_url %>

<script type="text/javascript">
$('#logout_runkeeper').on('click', function(){
  $(location).attr('href', '/');
});
</script>